if (WIN32)
  set(GUI_TYPE WIN32)
  
  if (MSVC)
    add_definitions("-D_MSC_VER")
    set(OS_NAME linux64)
    #set_property(GLOBAL PROPERTY INCLUDE_OS_NAME "win32" )
  else()
    if (CMAKE_SYSTEM_NAME MATCHES "cygwin")
      set(OS_NAME cygwin)
      #set_property(GLOBAL PROPERTY INCLUDE_OS_NAME "cygwin" )
    else()
      set(OS_NAME mingw)
      # set_property(GLOBAL PROPERTY INCLUDE_OS_NAME "mingw" )
    endif()
  endif()

elseif (APPLE)
  add_definitions(-DCPE_OS_MAC=1)
  set(OS_NAME mac)
  #set_property(GLOBAL PROPERTY INCLUDE_OS_NAME "mac" )
else()
  add_definitions(-DCPE_OS_LINUX=1)
  set(OS_NAME linux64)
  # set_property(GLOBAL PROPERTY INCLUDE_OS_NAME "linux64" )
endif()
