if (WIN32)
  set(GUI_TYPE WIN32)
  
  if (MSVC)
    set(OS_NAME vc)
  else()
    if (CMAKE_SYSTEM_NAME MATCHES "cygwin")
      set(OS_NAME cygwin)
    else()
      set(OS_NAME mingw)
    endif()
  endif()
elseif (APPLE)
  add_definitions(-DCPE_OS_MAC=1)
  set(OS_NAME mac)
else()
  add_definitions(-DCPE_OS_LINUX=1)
  set(OS_NAME linux64)
endif()

if (MSVC)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /wd4819 /wd4103 /wd4101 /wd4715 /wd4996")
endif ()
